name: Build Psych Engine 0.3.2 HTML5

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Haxe 4.1.5
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - name: Install and set Haxe Libraries (strict pinned versions, fully compatible)
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.7.0 --quiet
          haxelib install openfl 8.9.7 --quiet
          haxelib install flixel 4.7.0 --quiet
          haxelib install flixel-addons 2.8.0 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hxcpp 4.0.64 --quiet
          haxelib install tjson 1.4.0 --quiet
          haxelib install hscript 2.3.0 --quiet
          haxelib set lime 7.7.0
          haxelib set openfl 8.9.7
          haxelib set flixel 4.7.0
          haxelib set flixel-addons 2.8.0
          haxelib set flixel-ui 2.3.3
          haxelib set hxcpp 4.0.64
          haxelib set tjson 1.4.0
          haxelib set hscript 2.3.0

      - name: Build Psych Engine for HTML5 inside FNF-PsychEngine-0.4.2
        run: |
          cd FNF-PsychEngine-0.4.2
          haxelib run lime build html5 -debug

      - name: Move output to funkin folder
        run: |
          mkdir -p output/funkin
          cp -r FNF-PsychEngine-0.4.2/export/debug/html5/bin/* output/funkin/

      - name: Upload funkin folder (inside output/) as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: PsychEngineHTML5Build
          path: output
